test_dataloader_args: {
    dataset_name: img-mini-imagenet,
    dataset_args:
      {
        split: test,
        augment: default  # clip, default
      },
    sampler_name: metatasks-sampler,
    sampler_args: 
    {
      batch_num: 500,
      shot_num: 5,
      way_num: 15,
      query_num: 15
    },
    batch_size: 4
}

network_args:
  {
    model_name: resnet12,  # resnet12, clip
    model_args:
      { 
      },
    model_load_para:
      {
        load_old_encoder: /space1/zhaoqing/code/few_shot_meta_baseline/save/pre_meta_2_stage/linear/metabasepre2/max-tva.pth,
      },
}

similarity_method: cos  # 'cos', 'sqr'
