test_dataloader_args: {
    dataset_name: img-mini-imagenet,
    dataset_args:
      {
        split: test,
        patch_type: sampling,
        augment: default,  # clip, default
      },
    sampler_name: metatasks-sampler,
    sampler_args: 
    {
      batch_num: 2000,  # 500
      shot_num: 1,
      way_num: 5,
      query_num: 15
    },
    batch_size: 1  # 4 启用MVA训练模式的情况下, 每个batch的任务数只能为1
}

network_args:
  {
    model_name: patch-mva-network,
    model_args:
      {
        encoder_name: resnet12,  # resnet12, clip
        encoder_args: {},
        encoder_load_para:
          {
            load_old_encoder: /space1/zhaoqing/code/few_shot_meta_baseline/save/pre_meta_2_stage/linear/metabasepre2/max-tva.pth,
          },
        mva_name: dot-attention,
        mva_args: {
          update: False,
          w_type: none
        },
        task_info: {
          batch_size: 1,
          shot_num: 1,
          way_num: 5,
          query_num: 15
        },
        similarity_method: cos,  # 'cos', 'sqr'
        patch_mode: 'default'
      },
    model_load_para: {},
}


