test_dataloader_args: {
    dataset_name: mushi,
    dataset_args:
      {
        split: val,
        augment: clip,  # clip, default
        type: sim_data,
        shot_num: 0,
        query_num: 100,  # 所有数据作为测试集, 即: 共5类, 每类100张图像
        return_items: 3  # 返回三个值, 匹配mva测试
      },
    sampler_name: metatasks-sampler,
    sampler_args:  # 将所有数据sample成meta task, 每个task包含5-w 5-s 15-q
    {
      batch_num: 100,  # 500
      shot_num: 5,
      way_num: 5,
      query_num: 15
    },
    batch_size: 1  # 4
}

network_args:
  {
    model_name: mva-network,
    model_args:
      {
        encoder_name: clip,  # resnet12, clip
        encoder_args: {},
        encoder_load_para:
          {
            load_old_encoder: /space1/zhaoqing/code/few_shot_meta_baseline/save/pre_meta_2_stage/linear/metabasepre2/max-tva.pth,
          },
        mva_name: dot-attention,  # w-attention
        mva_args: {
          update: False  # True
        },
        task_info: {
          batch_size: 1,
          shot_num: 5,
          way_num: 5,
          query_num: 15
        },
        similarity_method: cos  # 'cos', 'sqr'
      },
    model_load_para: {},
}
