test_dataloader_args: {
    dataset_name: img-mini-imagenet,
    dataset_args:
      {
        split: test,
        augment: clip  # clip, default
      },
    sampler_name: metatasks-sampler,
    sampler_args: 
    {
      batch_num: 500,
      shot_num: 5,
      way_num: 5,
      query_num: 15
    },
    batch_size: 4
}

network_args:
  {
    model_name: mva-network,
    model_args:
      {
        encoder_name: clip,  # resnet12, clip
        encoder_args: {},
        encoder_load_para:
          {
            load_old_encoder: /space1/zhaoqing/code/few_shot_meta_baseline/save/pre_meta_2_stage/linear/metabasepre2/max-tva.pth,
          },
        mva_name: dot-attention,
        mva_args: {},
        task_info: {
          batch_size: 4,
          shot_num: 5,
          way_num: 5,
          query_num: 15
        },
        similarity_method: cos  # 'cos', 'sqr'
      },
    model_load_para: {},
}


