test_dataloader_args: {
    dataset_name: img-mini-imagenet,
    dataset_args:
      {
        split: test,
        augment: dafault
      },
    sampler_name: metatasks-sampler,
    sampler_args: 
    {
      batch_num: 200,
      shot_num: 1,
      way_num: 5,
      query_num: 15
    },
    batch_size: 4
}

network_args:
  {
    model_name: resnet12,
    model_args:
      { 
      },
    model_load_para:
      {
        load_pure_encoder: /space1/zhaoqing/code/graceful-few-shot/models/backbone/pretrained/resnet18-f37072fd.pth,
      },
    similarity_method: cos  # 'cos', 'sqr'
  }
