train_dataloader_args: {
    dataset_name: img-mini-imagenet,
    dataset_args:
      {
        split: train,
        patch_type: sampling,  # sampling, grid
        augment: default,  # clip, default
      },
    sampler_name: metatasks-sampler,
    sampler_args: 
    {
      batch_num: 2000,  # 500
      shot_num: 1,
      way_num: 5,
      query_num: 15
    },
    batch_size: 1  # 4 启用MVA训练模式的情况下, 每个batch的任务数只能为1
}

val_dataloader_args: {
    dataset_name: img-mini-imagenet,
    dataset_args:
      {
        split: val,
        patch_type: sampling,  # sampling, grid
        augment: default,  # clip, default
      },
    sampler_name: metatasks-sampler,
    sampler_args: 
    {
      batch_num: 200,  # 500
      shot_num: 1,
      way_num: 5,
      query_num: 15
    },
    batch_size: 1  # 4 启用MVA训练模式的情况下, 每个batch的任务数只能为1
}

network_args: {
    model_name: meta-patch-mva-network,
    model_args:
      {
        encoder_name: resnet12,  # resnet12, clip
        encoder_args: {},
        encoder_load_para:
          {
            # load_old_encoder: /space1/zhaoqing/code/few_shot_meta_baseline/save/pre_meta_2_stage/linear/metabasepre2/max-tva.pth,
            load_old_encoder: /space0/songk/code/graceful-few-shot/save/old_ckpt/pre_meta_2_stage/max-tva.pth,
          },
        mva_name: meta-attention,
        mva_args: {
          shot_num: 20,  # shot_num = patch_num*origin_shot_num, 14
          nor_type: l2_norm,  # 'softmax', 'l2_norm'
          similarity_method: 'pass'  # cos
        },
        task_info: {
          batch_size: 1,
          shot_num: 1,
          way_num: 5,
          query_num: 15
        },
        similarity_method: cos,  # 'cos', 'sqr'
        patch_mode: default,
        meta_info: {
          inner_epoch: 30,
          inner_lr: 0.1,
          inner_aug_type: 'zero',
          inner_choice_num: 2,
          inner_use_l1: False,
          inner_enhance_threshold: 0.0, 
          inner_enhance_top: 20,
          outer_epoch: 1,
          outer_optimizer_name: adam, # adam,
          outer_optimizer_args: {
            lr: 0.01,
            weight_decay: 5.e-4
          },
          outer_enhance_threshold: 0.6, 
          outer_enhance_top: 10,
          use_continue_loss: True,
          continue_loss_weight: 1.0,
          use_meta_loss: True,
          meta_loss_weight: 0.5
        },
      },
    model_load_para: {},
}

trainer_args: {
  full_epoch: 1000,
  save_epoch: 1
}
