# mix_train_dataloader_args:
#   {
#     dataset_name: mushi,
#     dataset_args:
#       {
#         split: train,
#         augment: resize,
#         type: mix_data,
#         shot_num: 175,
#         query_num: 75,
#       },
#     sampler_name: default-sampler,  # sequential-sampler, default-sampler
#     batch_size: 35,
#   }

mix_train_dataloader_args:
  {
    dataset_name: mushi,
    dataset_args:
      {
        split: train,
        augment: resize,
        type: mix_data,
        shot_num: 140,
        query_num: 60,
      },
    sampler_name: default-sampler,  # sequential-sampler, default-sampler
    batch_size: 70,
  }

sim_train_dataloader_args:
  {
    dataset_name: mushi,
    dataset_args:
      {
        split: train,
        augment: resize,
        type: sim_data,
        shot_num: 70,
        query_num: 30,
      },
    sampler_name: default-sampler,
    batch_size: 70,
  }

true_train_dataloader_args:
  {
    dataset_name: mushi,
    dataset_args:
      {
        split: train,
        augment: resize,
        type: true_data,
        shot_num: 140,  # 70
        query_num: 60,  # 30
      },
    sampler_name: default-sampler,
    batch_size: 70,  # 70
  }

sim_val_dataloader_args:
  {
    dataset_name: mushi,
    dataset_args:
      {
        split: val,
        augment: default,
        type: sim_data,
        shot_num: 70,
        query_num: 30,
      },
    sampler_name: default-sampler,
    batch_size: 30,
  }

# true_val_dataloader_args:
#   {
#     dataset_name: mushi,
#     dataset_args:
#       {
#         split: val,
#         augment: default,
#         type: true_data,
#         shot_num: 175,
#         query_num: 75,
#       },
#     sampler_name: default-sampler,
#     batch_size: 75,  # 75
#   }

true_val_dataloader_args:
  {
    dataset_name: mushi,
    dataset_args:
      {
        split: val,
        augment: default,
        type: true_data,
        shot_num: 140,
        query_num: 60,
      },
    sampler_name: default-sampler,
    batch_size: 60,  # 75
  }

network_args:
  {
    model_name: base-pretrain-network,
    model_args:
      {
        encoder_name: resnet18,
        encoder_args: {},
        encoder_load_para: 
          {
            load_pure_encoder: /space1/zhaoqing/code/graceful-few-shot/models/backbone/pretrained/resnet18-f37072fd.pth,
          },
        classifier_name: linear-classifier,
        classifier_args: {
            class_num: 5, # 5
          },
      },
  }

trainer_args:
  {
    optimizer_name: sgd,
    optimizer_args: { lr: 0.001, weight_decay: 5.e-4 },
    max_epoch: 100000,
    save_epoch: 200000,
  }
